name: 'Download JDK'
description: 'Download JDK from https://jdk.java.net'

branding:
  icon: 'download-cloud'
  color: 'orange'

inputs:
  feature:
    description: 'Feature number of the JDK to download'
    required: true
    default: '15'

outputs:
  file:
    description: 'The path to the downloaded file'
    value: '?'
  version:
    description: 'The feature version of the downloaded JDK'
    value: ${{ inputs.feature }}

runs:
  using: 'composite'
  steps:
    - name: 'Gather information'
      id: info
      shell: bash
      run: |
        action_os='linux-x64'
        action_os=$([ "${{ github.runner.os }}" = "macOS" ] && echo "osx-x64")
        action_os=$([ "${{ github.runner.os }}" = "Windows" ] && echo "windows-x64")
        action_properties='https://github.com/sormuras/bach/raw/HEAD/install-jdk.properties'
        action_url=$(wget --quiet --output-document - ${action_properties} | grep -i "${{ inputs.feature }}-${action_os}=" | awk -F "=" '{print $2}')
        echo ${action_url}
