name: test
on: push
jobs:
  jdk:
    name: "JDK ${{ matrix.feature }}"
    strategy:
      fail-fast: false
      matrix:
        feature: [15, 14, 13]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      id: jdk
      with:
        feature: ${{ matrix.feature }}
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ steps.jdk.outputs.version }}
        jdkFile: "${{ steps.jdk.outputs.file }}"
    - run: java --version
