name: test
on: push
jobs:
  jdk:
    name: "JDK ${{ matrix.feature }} on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        feature: [16, 15, 14, 13, 12, 11, 10, 9]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Checkout sources'
        uses: actions/checkout@v2
      - name: 'Download JDK'
        uses: ./
        id: jdk
        with:
          feature: ${{ matrix.feature }}
      - name: 'Set up JDK'
        uses: actions/setup-java@v1
        with:
          java-version: ${{ steps.jdk.outputs.version }}
          jdkFile: "${{ steps.jdk.outputs.file }}"
      - run: java --version
