name: test

on: [ push, pull_request ]

jobs:
  jdk:
    name: "JDK ${{ matrix.feature }} on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        feature: [ 16 ] # [ 16, 15, 14, 13, 12, 11, 10, 9 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Download JDK'
        id: download-jdk
        uses: sormuras/download-jdk@main
        with:
          feature: ${{ matrix.feature }}
#      - name: 'Set up JDK'
#        uses: actions/setup-java@v1
#        with:
#          java-version: ${{ steps.download-jdk.outputs.version }}
#          jdkFile: "${{ steps.download-jdk.outputs.file }}"
#      - run: java --version
